LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY BCD_7SEG IS
PORT ( 
	i_ENTRADA 	: IN STD_LOGIC_VECTOR(1 DOWNTO 0);
	i_RST 	: IN STD_LOGIC;
	A			: OUT STD_LOGIC;
	B			: OUT STD_LOGIC;
	C			: OUT STD_LOGIC;
	D			: OUT STD_LOGIC;
	E			: OUT STD_LOGIC;
	F			: OUT STD_LOGIC;
	G			: OUT STD_LOGIC
	);
END BCD_7SEG;
 
ARCHITECTURE BEHAVIORAL OF BCD_7SEG IS


BEGIN
PROCESS(i_ENTRADA,I_RST)
	BEGIN	
		IF (I_RST = '0') THEN
			A <= '0';
			B <= '0';
			C <= '0';
			D <= '0';
			E <= '0';
			F <= '0';
			G <= '0';
		ELSE
			A <= NOT((NOT i_ENTRADA(0)) OR i_ENTRADA(1));
			B <= NOT('1');
			C <= NOT(i_ENTRADA(0) OR NOT i_ENTRADA(1));
			D <= NOT((NOT i_ENTRADA(0)) OR i_ENTRADA(1));
			E <= NOT(NOT i_ENTRADA(0));
			F <= NOT((NOT i_ENTRADA(0)) AND (NOT i_ENTRADA(1)));
			G <= NOT(i_ENTRADA(1));
		END IF;
END PROCESS;
END BEHAVIORAL;
